### ISSUE TITLE
user_page

### ISSUE THREAD

**Issue by Sugyo-In** [flutterstudygn/stackoverflutter#15]

**Comment by HuanSuh** [comment]
로그인 작업 하고 마스터에 푸시했는데 그 브랜치에 UserDetailPage 더미로 넣어뒀어요.
거기서 작업하시면 될거같아요.

**Comment by HuanSuh** [comment]
로그인 기능은 localhost:8686 포트에서 테스트 하실 수 있습니다.
현재 vsCode에 launch.json 파일을 수정해둬서 vsCode로 실행하시면 8686포트로 붙을거에요.
android studio에서는 포트지정을 어떻게 하는지 잘 모르겠네요ㅠㅠㅠ

**Comment by Sugyo-In** [comment]
현재로선 딱히 할 부분이 없어 닫습니다. 나중에 필요하면 새로 이슈 만드는게 좋을 것 같아요.
