### ISSUE TITLE
Web 경험에 맞지 않는 page navigation.

### ISSUE THREAD

**Issue by Sugyo-In** [flutterstudygn/stackoverflutter#17]
같은 page의 링크를 여러번 하면 route stack에 같은 page가 여러번 중첩됨.
결과적으로 뒤로가기를 할 경우 이전에 있던 route path상의 전 page가 아닌 stack의 전 page가 나오게 됨.

**Comment by Sugyo-In** [comment]
플러터 공식 홈페이지에 기재되어있으며. [(링크)](https://flutter.dev/docs/development/platform-integration/web#how-are-forward-and-backward-buttons-presented-in-the-web-ui)

flutter/flutter#32248
위와 같이 이슈 등록되어 있습니다. 19년 4월에 등재됐으며 내용상으로 flutter-web을 unfork한 후에 진행할 것 같습니다. 아마도 해당 이슈가 flutter framework이 아닌 Android OS의 back button 같이 platform 의존적인 부분이라 그렇지 않을까싶습니다. unfork가 가지는 의미가 단순한 저장소의 unfork에 그치진 않을 것 같아 어느 정도의 사안인지는 알기 어려우나 적어도 beta 후기나 release 버전에 추가되지않을까 싶습니다. 

일단 현재로선 브라우저상의 navigation버튼을 사용하지 않고 app상에 navigation 버튼을 두어 이쪽의 사용을 유도하는게 바람직해 보입니다. 

확실하진 않지만 page navigation은 Navigator, NavigatorState, NavigatorOnserver를 상속해 구현할 수 있지 않을까싶습니다.

**Comment by Sugyo-In** [comment]
추가적으로 위의 내용을 구현에 있어 custom navigator를 사용해야하기 때문에 root navigator, 즉 MaterialApp의 navigator에는 사용할 수 없으며 MaterialApp을 간단하게 extends해서 해결 할 수도 없고해서 결국 중첩 navigator로 해결해야할 것 같습니다. 이 부분 관련 리팩토링이 선행되어야할 것 같은데 Navigator라 Route관련은 제가 맡아서 진행하면 어떨까요?

**Comment by HuanSuh** [comment]
넵! 아니면 custom navigator를 없애고 animation만 제거한 뒤에 header랑 menu부분도 다시 그리는 방법도 있을 것 같긴 하네요

**Comment by Sugyo-In** [comment]
Custom navigator를 사용하면 같은 페이지로 라우팅하는 부분이 쉽게 해결돼서요.

**Comment by Sugyo-In** [comment]
#27 로 이슈 병합
