### ISSUE TITLE
navigator

### ISSUE THREAD

**Issue by HuanSuh** [flutterstudygn/stackoverflutter#4]

**Comment by Sugyo-In** [comment]
이 이슈는 어떤 내용이죠? 만약 라우팅시 주소창에 경로가 안나오는 이슈라면 해당 onGenerateRoute에서 처리하는 경로가 materialApp의 routes에 등록되어있지 않아서 아닐까 추측해봅니다.

**Comment by HuanSuh** [comment]
기존에 PageTransition 시 animation 제거하는거랑 url 주소창에 안나오는 경우가 동시에 해결이 안되는 이슈였는데 해결되었습니다
